version: '3'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_DB: atrax
      POSTGRES_PASSWORD: example
    ports:
      - '5432:5432'

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    volumes:
      - .:/usr/src/app
    ports:
      - '8080:8080'
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://root:example@db:5432/atrax

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    volumes:
      - .:/usr/src/app
    ports:
      - '8082:8082'
    depends_on:
      - backend
